### ISSUE TITLE
Handling execution errors in Output

### ISSUE THREAD

**Issue by sok82** [datalayer/jupyter-ui#289]
I'm experimenting with version 0.17.0 having functionality of monitoring kernel phase introduced in https://github.com/datalayer/jupyter-ui/pull/282

And I'm experiencing a problem when execution finishes with error

Kernel phase monitoring works fine when execution finishes successfully, but when something is wrong with a code exception is thrown from kernel execution promise and I don't have an idea of how to catch it.

The way I trigger execution is just by increasing executionTrigger for output, so I don't control promise implicitly...

Exception example is

```
Uncaught Error TypeError: bar() missing 1 required positional argument: 'height'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 plt.bar(job_satisfaction_rate_train['job_satisfaction_rate'], color='green');

TypeError: bar() missing 1 required positional argument: 'height'
    at reject (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@lumino/coreutils/src/promise.ts:51:1)
    at _onReply (/Users/sk/Develop/src/jupyter/kernel/KernelExecutor.ts:262:1)
    at _handleReply (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@jupyterlab/services/src/kernel/future.ts:237:1)
    at handleMsg (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@jupyterlab/services/src/kernel/future.ts:219:1)
    at _handleMessage (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@jupyterlab/services/src/kernel/default.ts:1430:1)
    at <anonymous> (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@jupyterlab/services/src/kernel/default.ts:1595:1)
    --- Promise.then ---
    at KernelConnection._onWSMessage (/Users/sk/Develop/d20/d20-git-repo/d20-platform-wiki-editor-ui/node_modules/@jupyterlab/services/src/kernel/default.ts:1591:1)
```

Is there a chance to catch and process this exception?

What is a correct way of doing this?

In my case I just don't need this exception at all (because I have all the details in output which is enough), so for me it's better to suppress it (for example having some flag on output that will control suppression) in JS code and just pass exception description to output

**Comment by echarles** [comment]
jupyter-react 0.18.4 is released with this features.

Closing for now, please reopen if needed. Thx again.
